#############################################################
#
# prod 环境
#
#############################################################
server:
  port: 8088                  # web访问端口 约定为:80

spring:
  datasource:                                   # 数据源相关配置
    # url使用云服务器的内网ip
    url: jdbc:mysql://47.105.41.229:3306/mall-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: admin
    password: admin
  redis:
    database: 1
    ############# 单机模式 ############
    host: 47.105.41.229
    port: 6379
