#############################################################
#
# dev 环境
#
#############################################################
server:
  port: 8088                  # web访问端口 约定为:8088

spring:
  datasource:                                   # 数据源相关配置
    url: jdbc:mysql://localhost:3306/mall-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 1
    ############# 单机模式 ############
    host: 127.0.0.1
    port: 6379
    #################################

    ############# Redis Sentinel 哨兵模式 ############
#    sentinel:
#      master: master-name
#      nodes: 192.168.1.191:26379,192.168.1.191:26379,192.168.1.191:26379
    #################################

    ############# Redis cluster 集群模式 ############
#    cluster:
#      nodes: 192.168.1.201:6379,192.168.1.202:6379,192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379,192.168.1.206:6379
    #################################
